apiVersion: v1
kind: ConfigMap
metadata:
  name: https-check-configmap
data:
  hosts.txt: |
    www.chandz.com:443
    ww.baidu.com:443
    192.168.86.11:443
  crontab-list: |
    * * * * * for i in `cat /tmp/hosts.txt`; do bash /tmp/https-check $i; done
  https-check.sh: |
    #!/bin/bash
    # 加载环境变量
    touch /etc/default/locale
    sh -c "echo 'LANG=en_US.UTF-8' >> /etc/default/locale"
    sh -c "echo 'LC_ALL=en_US.UTF-8' >> /etc/default/locale"
    . /etc/default/locale
    
    #发送钉钉消息,机器人关键词证书
    send_message_dingtalk(){
        dingtalk_token="https://oapi.dingtalk.com/robot/send?access_token=钉钉群组添加自定义机器人获取token值"
        curl "$dingtalk_token" -H 'Content-Type: application/json' -d "{\"actionCard\": {\"text\": \"$context\",},\"msgtype\": \"actionCard\"}"
    }
    send_message_feishu(){
	      feishu_token=https://open.feishu.cn/open-apis/bot/v2/hook/"飞书群组添加自定义机器人获取token值"
        curl $feishu_token -X POST -H "Content-Type: application/json" -d "{\"msg_type\":\"text\", \"content\":{\"text\":\"$context\"}}"
    }

    https-check(){

        if [ $# -ne 1 ]; then
          echo "usage: /ssl-alert.sh www.baidu.com:443"
        else
            #计算SSL正式到期时间和当前时间的差值
            host=$1
            end_data=`date +%s -d "$(echo |timeout 30 openssl s_client -servername $host  -connect $host 2>/dev/null | openssl x509 -noout -dates|awk -F '=' '/notAfter/{print $2}')"`
            new_date=$(date +%s)
            days=$(expr $(expr $end_data - $new_date) / 86400)
           
           if [ $days -lt 300 ]; then
              context="您的$host 证书 还有${days}天到期  请及时处理"
              send_message_dingtalk
           fi
        fi
    }
    
    https-check $1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: https-check
  name: https-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-check
  template:
    metadata:
      labels:
        app: https-check
    spec:
      containers:
      - image: duanshuaixing02/databases-backup:v001
        imagePullPolicy: IfNotPresent
        name: https-check
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
          - name: https-check-volume
            mountPath: /etc/cron.d/crontab-list
            subPath: crontab-list
          - name: https-check-volume
            mountPath: /tmp/https-check.sh
            subPath: https-check.sh
          - name: https-check-volume
            mountPath: /tmp/hosts.txt
            subPath: hosts.txt
      volumes:
        - name: https-check-volume
          configMap:
            name: https-check-configmap
            defaultMode: 0777
