apiVersion: v1
kind: Service
metadata:
  name: external-network-nginx-proxy
  labels:
    app.kubernetes.io/name: nginx-proxy
    app.kubernetes.io/instance: external-network
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30808
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30809

  selector:
    app.kubernetes.io/name: nginx-proxy
    app.kubernetes.io/instance: external-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-network-nginx-proxy
  labels:
    app.kubernetes.io/name: nginx-proxy
    app.kubernetes.io/instance: external-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-proxy
      app.kubernetes.io/instance: external-network
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-proxy
        app.kubernetes.io/instance: external-network
    spec:
      containers:
        - name: nginx-proxy
          securityContext:
            null
          image: "registry.baidubce.com/tools/nginx-proxy:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
