---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntpd-conf
data:
  ntp.conf: |
    driftfile /var/lib/ntp/ntp.drift
    restrict default nomodify notrap
    #upstream
    server cn.pool.ntp.org  prefer
    server 1.cn.pool.ntp.org iburst
    server 2.cn.pool.ntp.org iburst
    server cn.ntp.org.cn iburst

    # performance
    tinker panic 0
    tos maxclock 8
    tos minclock 3

    #client-config /etc/ntp.conf
    #driftfile /var/lib/ntp/ntp.drift
    #leapfile /usr/share/zoneinfo/leap-seconds.list
    #server net-server-ip prefer
---
apiVersion: v1
kind: Service
metadata:
  name: ntpd
spec:
  selector:
    app: ntpd
  ports:
  - name: ntp-udp
    port: 123
    protocol: UDP
    targetPort: 123
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntpd
  template:
    metadata:
      labels:
        app: ntpd
    spec:
      containers:
      - name: ntpd
        image: duanshuaixing02/ntpd:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - SYS_TIME
            - SYS_NICE
          privileged: false
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 123
          protocol: UDP
        livenessProbe:
          exec:
            command:
            - ntpq
            - -p
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - ntpq
            - -p
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: ntp-conf
          mountPath: /etc/ntp.conf
          subPath: ntp.conf
      volumes:
      - name: ntp-conf
        configMap:
          name: ntpd-conf
          items:
          - key: ntp.conf
            path: ntp.conf
---
