apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chandz-com-tls
spec:
  secretName: chandz-com-tls
  dnsNames:
  - chandz.com
  - "*.chandz.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
